# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack Szklarz
email: jsduck03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jack Szklarz
baseurl: "" # the subpath of your site, e.g. /blog
url: "jsduck03.github.io" # the base hostname & protocol for your site

github_username:  jsduck03

# Build settings
markdown: kramdown
